crowbar/barclamp-neutron

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb

This requires the following patches in neutron to be backported to Icehouse:
https://review.openstack.org/#/c/88673/
https://review.openstack.org/#/c/87085/
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=912647

Add "insecure" and ca cert options to nova notification (bnc#912647)

---

chef/cookbooks/neutron/recipes/post_install_conf.rb

This line is not needed any more, it cause overwriting
segmentation_id when openvswitch and vlan mode is chose.

Fix for OpenVSwitch with VLAN mode

---

chef/cookbooks/neutron/recipes/common_config.rb

The line defining the variable is:
nova_ssl_cacerts = nova[:nova][:ssl][:ca_certs] unless nova_insecure
nova_ssl_cacerts will be set to nil if nova_insecure is true. And "||
nil" has no impact on empty strings, so it's just redundant.

Remove || nil that makes no sense

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/recipes/server.rb
chef/roles/neutron-server.rb

They where only executed on the server anyway. This also gets us rid of
the the "neutron_server" attribute.

Move SSL related checks to server recipe

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

This confuses the metadata agent and causes it to fail on startup.

Make sure to not write an empty database setting to neutron.conf

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

If you run with multiple_api workers there is a race condition in the nsx sync backend as we start reading from the database before it's connected if running with 1 worker this doesn't occur as things don't occur concurrently.
https://bugs.launchpad.net/neutron/+bug/1354226
and
https://bugzilla.suse.com/show_bug.cgi?id=915572

Disable multiple_api workers when core_plugin vmware (bnc#915572)

---

chef/cookbooks/neutron/recipes/server.rb

We overlooked these two instances when enabling support for multiple ml2 type
drivers.

Fix cisco nexus support

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb

Everywhere else, we rely on the admins to either properly install their
CA certificate system-wide, or to use the insecure options in the
barclamps.

Do not set nova_ca_certificates_file

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

Properly use the non-deprecated Keystone middleware config settings

Use auth_uri/identity_uri

---

chef/cookbooks/neutron/recipes/database.rb
chef/cookbooks/neutron/recipes/l3_ha.rb
chef/cookbooks/neutron/recipes/server_ha.rb

There are two cases where two non-founder nodes can do the same LWRP at the same time, resulting in unexpected failures. I don't think we really need this.

Fix races on 3-node HA clusters

---

chef/cookbooks/neutron/recipes/l3_ha.rb
chef/cookbooks/neutron/recipes/server_ha.rb

Neutron depends on Keystone and RabbitMQ to be started first

HA: Set Optional  ordering for Neutron startup

---

chef/cookbooks/neutron/recipes/l3.rb
chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb

This depends on https://github.com/crowbar/barclamp-nova/pull/438

Use SSL to talk to nova-metadata when SSL is enabled for nova

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/templates/default/linuxbridge_conf.ini.erb
chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb
chef/cookbooks/neutron/templates/default/ovs_neutron_plugin.ini.erb
chef/data_bags/crowbar/bc-template-neutron.json
chef/data_bags/crowbar/bc-template-neutron.schema
chef/data_bags/crowbar/migrate/neutron/025_use_l2pop.rb
crowbar_framework/app/models/neutron_service.rb

This is only possible when VXLAN or GRE is used.
For more details about L2 population, see
http://docs.openstack.org/admin-guide-cloud/content/ml2_l2pop_scenarios.html
and https://wiki.openstack.org/wiki/L2population
This comes on top of https://github.com/crowbar/barclamp-neutron/pull/206

Enable L2 population mechanism driver

---

chef/cookbooks/neutron/recipes/server.rb

Is avoids having to update the paths in two places when changes are required.

Use sysconfig file to figure out the db-migrate arguments

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/neutron/templates/default/ovs_neutron_plugin.ini.erb
chef/data_bags/crowbar/bc-template-neutron.json
chef/data_bags/crowbar/bc-template-neutron.schema
chef/data_bags/crowbar/migrate/neutron/026_rename_l3_role.rb
chef/data_bags/crowbar/migrate/neutron/027_use_dvr.rb
chef/roles/neutron-l3.rb
chef/roles/neutron-network.rb
crowbar_framework/app/models/neutron_service.rb

**Please note that this PR includes https://github.com/crowbar/barclamp-neutron/pull/209**
*First commit:*
As the L3 agent will also run on compute host, this name makes no sense.
And we really reference such nodes as network nodes, so it makes more
sense this way.
*Second commit:*
DVR stands for Distributed Virtual Routers, see
https://github.com/openstack/neutron-specs/blob/master/specs/juno/neutron-ovs-dvr.rst
https://wiki.openstack.org/wiki/Neutron/DVR
The implementation is loosely based on what's in
https://wiki.openstack.org/wiki/Neutron/DVR/HowTo
For DVR, the L3 agent needs to run not just on the network node, but
also on compute nodes. So the configuration for this has to move to the
common code path.
When using HA, we still setup the L3 agent with pacemaker on the network
nodes, …

Add support for DVR

---

chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
chef/cookbooks/neutron/templates/default/dnsmasq-neutron.conf.erb

this avoids fragmentation as per
http://docs.openstack.org/admin-guide-cloud/content/openvswitch_plugin.html
and avoids networking problems with SLE12 compute hosts and GRE
https://bugzilla.suse.com/show_bug.cgi?id=917328

use lower MTU value for GRE tunnels (bnc#917328)

---

crowbar_framework/app/assets/javascripts/barclamps/neutron/application.js
crowbar_framework/app/models/neutron_service.rb

L2 population doesn't work with vlan-only, so we need to disable it in
that case. But we still want to use it by default when possible, so use
some javascript magic.

webui: Automatically enable/disable l2pop depending on used types

---

chef/cookbooks/neutron/recipes/common_config.rb

This is needed when keystone is deployed with SSL certs
that dont cover all internal hostnames (aka insecure),
but nova is not deployed with HTTPS,
so the insecure flag is missing there.
https://bugzilla.suse.com/show_bug.cgi?id=895594
This is very much like https://github.com/crowbar/barclamp-nova/pull/445

allow nova-access to work with ssl-keystone (bnc#895594)

---

chef/cookbooks/neutron/recipes/common_agent.rb

The neutron packages are installed too late and we end up with this
error:
```
[2015-04-22T15:01:23+00:00] INFO: Processing ruby_block[edit /etc/sysctl.conf for rp_filter] action create (neutron::common_agent line 26)
[2015-04-22T15:01:23+00:00] INFO: ruby_block[edit /etc/sysctl.conf for rp_filter] called
[2015-04-22T15:01:23+00:00] INFO: Processing directory[create /etc/sysctl.d for disable-rp_filter] action create (neutron::common_agent line 35)
[2015-04-22T15:01:23+00:00] INFO: Processing cookbook_file[/etc/sysctl.d/50-neutron-disable-rp_filter.conf] action create (neutron::common_agent line 41)
[2015-04-22T15:01:23+00:00] INFO: Processing bash[reload disable-rp_filter-sysctl] action nothing (neutron::common_agent line 46)
[2015-04-22T15:01:23+00:00] INFO: Processing …
```

Fix setup of compute nodes when using linuxbridge

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

Will need backporting to tex and maybe stoney too.
Requires corresponding change in neutron-ha-tool:
https://build.suse.de/request/show/57156

pass keystone admin password to neutron-ha-tool via file (bsc#922751)

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb

neutron-ha-tool replicates the dhcp only on start which is wrong an
causes new networks to be not replicated to the available dhcp-agent
this change effects that neutron keeps care about this behavior

Set dhcp_agents_per_network option in neutron.conf

---

crowbar_framework/app/models/neutron_service.rb

It is fixing https://bugzilla.suse.com/show_bug.cgi?id=934688
```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/neutron/recipes/l3.rb
================================================================================
NoMethodError
-------------
undefined method `first' for nil:NilClass
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/neutron/recipes/vmware_support.rb:96:in `from_file'
/var/chef/cache/cookbooks/neutron/recipes/common_agent.rb:196:in `from_file'
/var/chef/cache/cookbooks/neutron/recipes/l3.rb:17:in `from_file'
Relevant File Content:
----------------------
/var/chef/cache/cookbooks/neutron/recipes/vmware_support.rb:
89:    command "ovs-vsctl br-set-external-id br1 bridge-id br1"
90: …
```

Allocate SDN IP for NSX nodes, (bnc#934688)

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb

Backport of #221
neutron-ha-tool replicates the dhcp only on start which is wrong an
causes new networks to be not replicated to the available dhcp-agent.
This change effects that neutron keeps care about this behavior.
(cherry picked from commit a674f11ab30f86d74cc7ec29bc0c1086e1598441)

[tex] Set dhcp_agents_per_network option (bsc#928189)

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/data_bags/crowbar/bc-template-neutron.json
chef/data_bags/crowbar/bc-template-neutron.schema
chef/data_bags/crowbar/migrate/041_add_max_header_line.rb

Depends on: https://github.com/crowbar/barclamp-neutron/pull/197 and https://github.com/crowbar/barclamp-keystone/pull/280
Note there are currently a few places where the keystone v3 api is not supported by neutron (mostly neutron-ha-tool, still need to check what's breaking v3 for the metadata agent). In those place the v2 URL is still used for now.

Allow switching the Keystone API version

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
chef/cookbooks/neutron/templates/default/linuxbridge_conf.ini.erb
chef/cookbooks/neutron/templates/default/ovs_neutron_plugin.ini.erb
chef/data_bags/crowbar/bc-template-neutron.json
chef/data_bags/crowbar/bc-template-neutron.schema
chef/data_bags/crowbar/migrate/neutron/042_additional_external_networks.rb
crowbar_framework/app/models/neutron_service.rb

Enable multiple external network for Neutron.
Some manual steps are still needed and will be documented in the
official documentation.

Enable setting multiple external networks

---

chef/cookbooks/neutron/metadata.rb

Needed if the cookbook is used without the crowbar framework. I.e. using
the cookbook as berkshelf dependency.
Also update maintainer email address.

Set cookbook name in metadata

---

chef/cookbooks/neutron/templates/default/ovs-usurp-config.erb

Temporal workaround for bsc#930986 proposed by rhafer.
A better workaround based on
https://en.opensuse.org/Portal:Wicked/OpenvSwitch is in
planning.

Update the interface in ovs-usurp-config service

---

chef/cookbooks/neutron/recipes/common_config.rb
crowbar_framework/app/models/neutron_service.rb

When nova-multi-controller and neutron-server are deployed
on two different nodes, the neutron.conf was not properly updated
with the nova settings because it could't find the node. Search
for the instance (optional since normal deployment order currently
is neutron first, then nova) properly so that get_instance()
in the chef recipe can do its job.

Fix search for nova instance

---

chef/cookbooks/neutron/recipes/common_agent.rb

The compute nodes don't need that, unless DVR is used.

Do not add bridge mappings for external networks on compute nodes

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

This requires excessive amount of memory and causes the mkcloud
runs to fail randomly. In addition this is marked as experimental
upstream and currently not well tested.

Do not run multiple api/rpc processes

---

chef/cookbooks/neutron/recipes/common_agent.rb

There seems to be a problem and we have revert-external-network.patch
in our rpm package to revert the support.
So multiple external network support needs some rework and we disable
it for now.

Disable multiple external network support

---

chef/cookbooks/neutron/recipes/common_agent.rb

Commit 18e8e32ab23ce0c112bc281594718f8d6a987cb2 disabled
multiple extenal networks support but the commit is incomplete.
The code raises a "NameError" now because the variable
"multiple_external_networks" is not defined.

Disable multiple external networks fix

---

chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb

The default behavior of starting #cpu/2 "extra" agents makes
more sense, but still give it a top of 4 metadata agents.

Be conservative with starting metadata agents

---

chef/cookbooks/neutron/recipes/common_agent.rb

The l3-agent needs the fwaas package. Otherwise you get:
ERROR neutron.services.firewall.agents.l3reference.firewall_l3_agent \
FWaaS plugin is configured in the server side,
but FWaaS is disabled in L3-agent.
and the l3 agent service can not start.

Install fwaas packages on the neutron-network role node

---

chef/cookbooks/neutron/recipes/common_agent.rb

With the underlying regression fixed, we can reenable the
support for multiple external networks.
This reverts commit 18e8e32ab23ce0c112bc281594718f8d6a987cb2.

Revert "Disable multiple external network support"
